# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/debugbar',
                'doc_host': 'https://itepifanio.github.io',
                'git_url': 'https://github.com/itepifanio/debugbar',
                'lib_path': 'debugbar'},
  'syms': {'debugbar.core': {'debugbar.core.foo': ('core.html#foo', 'debugbar/core.py')}}}
